### PR TITLE
feat: Added Timer functionality

### PR DESCRIPTION
**Pull request by Devansu-Yadav**
Changes:
- Created the Timer component.
- Added Timer functionalities like Start, Stop, Restart.
- Made the components/page responsive.

Preview link to the changes:- https://deploy-preview-3--bluemodoro-app.netlify.app/

### CODE REVIEW

**Review by someshtiwarii — APPROVED** [review]
clean UI! looks good to me

**Review by bipin7yadav — APPROVED** [review]
good to merge

**Review by NtshVrm — APPROVED** [review]
No suggestions in particular
- Very Clean UI
- Easy to use
- Well Structured and easy to read

**Review by preethasri — APPROVED** [review]
good to merge

**Comment by SadiqZak** [comment]
The UI looks really cool and is really smooth. Brownie points +

**Pull request merged**
